### ISSUE TITLE
The Discord link is not an invite link

### ISSUE THREAD

**Issue by boredstiff** [RustyDAW/Are-We-DAW-Yet#4]
It's just a link to a channel inside of your Discord.

**Comment by BillyDM** [comment]
I think Discord automatically shows an invite to a public server if you're not a member.

**Comment by boredstiff** [comment]
That is incorrect. If I had been able to join the group automatically, I wouldn't have filed the issue. Clicking the link just takes you to your own Discord home page and does not invite you to the server.

The link posted in the README is this: https://discord.com/channels/590254806208217089/590283781806620672

An invitation link looks like this: https://discord.gg/kYpWT6wu

You can generate an invitation link by clicking the drop down next to the server name and then clicking Invite People

![image](https://user-images.githubusercontent.com/3489076/107546696-80282580-6b81-11eb-901b-ff5847220578.png)

![image](https://user-images.githubusercontent.com/3489076/107546771-959d4f80-6b81-11eb-97a5-0c58bdadd870.png)

Which will then give you a link at the bottom of the next screen.

![image](https://user-images.githubusercontent.com/3489076/107546904-b8c7ff00-6b81-11eb-8c94-27db01fea5e7.png)

To change the time frame for the invite to be infinite and never expire, click the Edit Invite Link text at the bottom.

**Comment by BillyDM** [comment]
Oh, gotcha! Thanks for pointing this out. :)
